int _putchar(char c);
void print_alphabet(void);
print_alphabet_x10(void);
_islower(int c);
_isalpha(int c);
int print_sign(int n);
int _abs(int n);
int print_last_digit(int n);
void jack_bauer(void);
void times_table(void);
int add(int a, int b);
void print_to_98(int n);
void print_times_table(int n);
void putformat(int);
print alphabet_x10(void);
int _islower(int c);
int _isalpha(int c);
